name: Build iOS IPA with Flutter

on:
  push:
    branches:
      - main # O la rama que uses para tu código principal

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # Asegúrate de que esta sea la versión de Flutter que usas o una compatible.
          # Basado en tu error anterior, prueba con '3.32.8' o 'latest'
          flutter-version: 'latest' # O '3.32.8' si quieres una versión específica

      - name: Get Flutter dependencies
        run: flutter pub get

      # ESTE ES EL PASO CRÍTICO QUE DEBE ESTAR PRESENTE
      - name: Build iOS (Release)
        run: flutter build ios --release --no-codesign

      - name: Archive IPA
        run: |
          mkdir -p build/ipa
          # Intentar encontrar el .app bundle en diferentes ubicaciones comunes
          APP_PATH=$(find build/ios -name "*.app" -maxdepth 3) # Búsqueda inicial más amplia

          if [ -z "$APP_PATH" ]; then
            echo "Error: No .app bundle found with initial wide search. Checking specific build paths..."
            if [ -d "build/ios/iphoneos" ]; then
              APP_PATH=$(find build/ios/iphoneos -name "*.app" -maxdepth 1)
            elif [ -d "build/ios/Release-iphoneos" ]; then
              APP_PATH=$(find build/ios/Release-iphoneos -name "*.app" -maxdepth 1)
            elif [ -d "build/ios/Debug-iphoneos" ]; then
              APP_PATH=$(find build/ios/Debug-iphoneos -name "*.app" -maxdepth 1)
            fi
          fi

          if [ -z "$APP_PATH" ]; then
            echo "Error: Still no .app bundle found after checking all common paths. Check 'Build iOS (Release)' logs for exact output path."
            exit 1 # Forzar el fallo del workflow si no se encuentra el .app
          else
            echo "Found .app bundle at: $APP_PATH"
            # Copiar el .app al directorio de artifacts
            cp -r "$APP_PATH" build/ipa/Runner.app
            echo "Copied Runner.app to build/ipa/"
          fi

      - name: Upload .app bundle as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-app-ios-bundle
          path: build/ipa/Runner.app
